import { Artwork, ArtCategory } from './types';

export const ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Midnight Serenade',
    artist: 'Benard Mugambi',
    category: ArtCategory.PAINTING,
    price: 4500,
    dimensions: '48" x 60"',
    year: 2023,
    description: 'A moody exploration of city lights reflecting on rain-slicked streets, capturing the solitude of the urban night. Thick impasto oil strokes contrast with delicate glazes.',
    imageUrl: 'https://picsum.photos/id/1016/800/1000',
    available: true,
  },
  {
    id: '2',
    title: 'Ephemeral Bloom',
    artist: 'Benard Mugambi',
    category: ArtCategory.PAINTING,
    price: 3200,
    dimensions: '36" x 36"',
    year: 2024,
    description: 'An abstract interpretation of spring flora in decay. The vibrant pinks and reds are violently interrupted by charcoal greys, symbolizing the fleeting nature of beauty.',
    imageUrl: 'https://picsum.photos/id/106/800/800',
    available: true,
  },
  {
    id: '3',
    title: 'Study of Silence',
    artist: 'Benard Mugambi',
    category: ArtCategory.PENCIL,
    price: 1200,
    dimensions: '18" x 24"',
    year: 2022,
    description: 'A hyper-realistic graphite study of a lone figure. The heavy shading creates a sculpture-like depth on the flat paper, representing the stoic witness of history.',
    imageUrl: 'https://picsum.photos/id/1069/800/1000',
    available: true,
  },
  {
    id: '4',
    title: 'Digital Horizon V',
    artist: 'Benard Mugambi',
    category: ArtCategory.PAINTING,
    price: 1850,
    dimensions: '24" x 36"',
    year: 2024,
    description: 'Acrylic on canvas. A manual reproduction of digital glitches, exploring the intersection of algorithmic chaos and human-curated color palettes.',
    imageUrl: 'https://picsum.photos/id/1048/800/600',
    available: true,
  },
  {
    id: '5',
    title: 'Crimson Tide',
    artist: 'Benard Mugambi',
    category: ArtCategory.PAINTING,
    price: 5600,
    dimensions: '50" x 70"',
    year: 2021,
    description: 'A large-scale seascape that borders on abstraction. The overwhelming power of the ocean is depicted through aggressive knife work and a monochromatic red palette.',
    imageUrl: 'https://picsum.photos/id/1050/900/1200',
    available: false,
  },
  {
    id: '6',
    title: 'Fractured Memory',
    artist: 'Benard Mugambi',
    category: ArtCategory.PENCIL,
    price: 2800,
    dimensions: '30" x 40"',
    year: 2023,
    description: 'Graphite and charcoal on textured paper. A commentary on how memory degrades, featuring erased sections and rewritten lines.',
    imageUrl: 'https://picsum.photos/id/1056/800/1000',
    available: true,
  },
  {
    id: '7',
    title: 'Golden Solstice',
    artist: 'Benard Mugambi',
    category: ArtCategory.PAINTING,
    price: 3800,
    dimensions: '40" x 40"',
    year: 2023,
    description: 'Warm, radiating gold leaf applied over a textured dark acrylic background. The piece changes character dramatically depending on the angle of light.',
    imageUrl: 'https://picsum.photos/id/1080/800/800',
    available: true,
  },
  {
    id: '8',
    title: 'Urban Decay Sketch',
    artist: 'Benard Mugambi',
    category: ArtCategory.PENCIL,
    price: 900,
    dimensions: '14" x 18"',
    year: 2022,
    description: 'Detailed pencil work featuring rust, concrete, and steel. A brutalist appreciation of industrial structures reclaiming their space in nature.',
    imageUrl: 'https://picsum.photos/id/1033/800/600',
    available: true,
  }
];